spring.application.name=SeatFlow

spring.datasource.url=${SEATFLOW_DB_URL:jdbc:mysql://127.0.0.1:3306/seatflow}
spring.datasource.username=${SEATFLOW_DB_USERNAME:seatflow_app}
spring.datasource.password=${SEATFLOW_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
